addSbtPlugin("org.jetbrains" % "sbt-ide-settings" % "1.1.0")
addSbtPlugin("org.scalameta" % "sbt-scalafmt"     % "2.5.2")
addSbtPlugin("com.eed3si9n"  % "sbt-assembly"     % "0.15.0")
addSbtPlugin("org.scoverage" % "sbt-scoverage"    % "1.8.2")
//addSbtPlugin("io.spray"      % "sbt-revolver"     % "0.10.0")
